# Generated by Django 4.1.7 on 2023-04-06 03:26

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
